### ISSUE TITLE
calculation of next_visit?

### ISSUE THREAD

**Issue by karishmas26** [USAID-OHA-SI/Aging#4]
https://github.com/USAID-OHA-SI/Aging/blob/1a351ffa0808c69e9146fe47465b560e60b2f7f0/aging.qmd#L347-L350

current code orders by `visit_date` which creates a `next_visit_date` that is exactly equal to `visit_date`. As such, it causes some downstream calculations (like `visit_gap_actual` to be 0).

I changed the order by to `id` instead and it seems to work? but just adding here as an issue for you to review since we are not sure

`test <- merged_visits_data %>% 
  arrange(id, visit_date) %>% 
  mutate(next_visit_date = lead(visit_date, order_by = id),
         .by = id)
`

**Comment by karishmas26** [comment]
also, if we are seeing a return to treatment for someone that doesnt have a visit within the allotted time, then should that be an ITT/RTT? vs if someone does not visit in the allotted time frame and then do not have another `next_visit` then they are truly `ltfu`

**Comment by achafetz** [comment]
Since we have already ordered by visit date in ln 348, we don't actually need to have it in ln349. But the ideas is within each `id`, we want to order by their `visit_date` and then take the next date that exists. 

Having an actual gap of 0 days may be a result of being seen in a different part of the hospital or coming back to get ART or may just be an entry issue? But the code logic is sound. These two are equal, whether or not you include `order_by = visit_date`. 

```
merged_visits_data %>% 
  arrange(id, visit_date) %>% 
  mutate(next_visit_date = lead(visit_date, order_by = visit_date),
         .by = id) %>% 
  mutate(next_visit_date_alt = lead(visit_date),
         .by = id) %>% 
  filter(next_visit_date != next_visit_date_alt)
```
